#!/usr/bin/env bash
#
# Build script for pve-install.sh
# Concatenates all source modules into a single deployable script
#

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SRC_DIR="$SCRIPT_DIR/src"
OUTPUT_FILE="$SCRIPT_DIR/../pve-install.sh"

echo "Building pve-install.sh..."

# Check if source directory exists
if [ ! -d "$SRC_DIR" ]; then
    echo "Error: Source directory not found: $SRC_DIR"
    exit 1
fi

# Create output file with header
cat > "$OUTPUT_FILE" << 'HEADER'
#!/usr/bin/env bash
# =============================================================================
# Proxmox VE Auto-Installer for Hetzner Dedicated Servers
# =============================================================================
# This file is auto-generated by build.sh - DO NOT EDIT DIRECTLY
# Edit the source files in scripts/src/ instead
#
# Source modules:
#   00-header.sh     - Colors and initial setup
#   01-helpers.sh    - Helper functions (SSH, download, progress)
#   02-validation.sh - Input validation functions
#   03-hardware.sh   - Hardware detection
#   04-input.sh      - User input collection
#   05-packages.sh   - Package installation and ISO download
#   06-qemu.sh       - QEMU installation functions
#   07-configure.sh  - Post-installation configuration
#   99-main.sh       - Main execution flow
# =============================================================================

HEADER

# Concatenate all source files in order
for src_file in "$SRC_DIR"/*.sh; do
    if [ -f "$src_file" ]; then
        echo "  Adding: $(basename "$src_file")"
        echo "" >> "$OUTPUT_FILE"
        echo "# --- $(basename "$src_file") ---" >> "$OUTPUT_FILE"
        # Skip shebang lines from subsequent files (only keep first one)
        if [ "$(basename "$src_file")" = "00-header.sh" ]; then
            tail -n +2 "$src_file" >> "$OUTPUT_FILE"
        else
            cat "$src_file" >> "$OUTPUT_FILE"
        fi
    fi
done

# Make executable
chmod +x "$OUTPUT_FILE"

echo ""
echo "Build complete: $OUTPUT_FILE"
echo "Lines: $(wc -l < "$OUTPUT_FILE")"
